# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63d1461779db08734b29f3ea059e8edff9101e28156dc51615b13cdd679a83d62ebec4b77563ee157402e83c51df6bd280a3b57cdeb63213a9a1137118074610

test:
  secret_key_base: a121958ed0f3174c9a09765591d601a839ae482a28054a500437cd83faf418222a137d22991974edc5cb95a8a133991f8a6f5c52d15f5aee435d014fa23b240b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
